-- ./lua/death_face/config/zt_zdf.lua
return {
    -- ============================================================================
    -- 形态键配置（基于另一 MOD 实际表现优化）
    -- 濒死阶段：半闭眼、悲伤眉、轻微张嘴、嘴角下压
    -- 强直阶段：睁眼、牙关紧闭、嘴角后缩、眼球上翻
    -- 死后阶段：半闭眼、表情松弛
    -- ============================================================================
    flexConfig = {
        -- ===================================
        -- 眼睑 / 闭眼
        -- ===================================
        blink = {
            oscillateBase = 0.75,
            oscillateAmp = 0.05,
            oscillateFreq = 2.0,
            fadeTarget = 0.25,
            spikeTarget = 0.05,
        },
        eyelid_blink_left = {
            oscillateBase = 0.75,
            oscillateAmp = 0.05,
            oscillateFreq = 2.2,
            fadeTarget = 0.22,
            spikeTarget = 0.05,
        },
        eyelid_blink_right = {
            oscillateBase = 0.75,
            oscillateAmp = 0.05,
            oscillateFreq = 2.2,
            fadeTarget = 0.22,
            spikeTarget = 0.05,
        },
        eyelid_wink = {
            oscillateBase = 0,
            oscillateAmp = 0,
            oscillateFreq = 0,
            fadeTarget = 0,
            spikeTarget = 0,
        },
        eyelid_wink_left = {
            oscillateBase = 0,
            oscillateAmp = 0,
            oscillateFreq = 0,
            fadeTarget = 0,
            spikeTarget = 0,
        },
        eyelid_wink_right = {
            oscillateBase = 0,
            oscillateAmp = 0,
            oscillateFreq = 0,
            fadeTarget = 0,
            spikeTarget = 0,
        },
        eyelid_pain = {
            oscillateBase = 0.60,
            oscillateAmp = 0.10,
            oscillateFreq = 2.0,
            fadeTarget = 0.15,
            spikeTarget = 0.05,
        },
        eyelid_pain_left = {
            oscillateBase = 0.40,
            oscillateAmp = 0.08,
            oscillateFreq = 2.2,
            fadeTarget = 0.10,
            spikeTarget = 0.05,
        },
        eyelid_pain_right = {
            oscillateBase = 0.40,
            oscillateAmp = 0.08,
            oscillateFreq = 2.2,
            fadeTarget = 0.10,
            spikeTarget = 0.05,
        },
        eyelid_surprised = {
            oscillateBase = 0,
            oscillateAmp = 0,
            oscillateFreq = 0,
            fadeTarget = 0,
            spikeTarget = 0,
        },
        eyelid_surprised2 = {
            oscillateBase = 0,
            oscillateAmp = 0,
            oscillateFreq = 0,
            fadeTarget = 0,
            spikeTarget = 0,
        },
        eyelid_sad = {
            oscillateBase = 0,
            oscillateAmp = 0,
            oscillateFreq = 0,
            fadeTarget = 0,
            spikeTarget = 0,
        },
        eyelid_sad2 = {
            oscillateBase = 0,
            oscillateAmp = 0,
            oscillateFreq = 0,
            fadeTarget = 0,
            spikeTarget = 0,
        },
        eyelid_smile = {
            oscillateBase = 0,
            oscillateAmp = 0,
            oscillateFreq = 0,
            fadeTarget = 0,
            spikeTarget = 0,
        },
        eyelid_angry = {
            oscillateBase = 0,
            oscillateAmp = 0,
            oscillateFreq = 0,
            fadeTarget = 0,
            spikeTarget = 0,
        },
        eyelid_angry2 = {
            oscillateBase = 0,
            oscillateAmp = 0,
            oscillateFreq = 0,
            fadeTarget = 0,
            spikeTarget = 0,
        },
        eyelid_squeeze = {
            oscillateBase = 0.70,
            oscillateAmp = 0.10,
            oscillateFreq = 2.5,
            fadeTarget = 0.20,
            spikeTarget = 0.0,
        },
        eyelid_smug = {
            oscillateBase = 0,
            oscillateAmp = 0,
            oscillateFreq = 0,
            fadeTarget = 0,
            spikeTarget = 0,
        },

        -- ===================================
        -- 眉毛
        -- ===================================
        brows_angry = {
            oscillateBase = 0.35,
            oscillateAmp = 0.08,
            oscillateFreq = 2.0,
            fadeTarget = 0,
            spikeTarget = 0.45,
        },
        brows_sad = {
            oscillateBase = 0.70,
            oscillateAmp = 0.10,
            oscillateFreq = 1.8,
            fadeTarget = 0.05,
            spikeTarget = 0.75,
        },
        brows_sad2 = {
            oscillateBase = 0.60,
            oscillateAmp = 0.10,
            oscillateFreq = 2.0,
            fadeTarget = 0.05,
            spikeTarget = 0.65,
        },
        brows_bored = {
            oscillateBase = 0,
            oscillateAmp = 0,
            oscillateFreq = 0,
            fadeTarget = 0,
            spikeTarget = 0,
        },
        brows_bored2 = {
            oscillateBase = 0,
            oscillateAmp = 0,
            oscillateFreq = 0,
            fadeTarget = 0,
            spikeTarget = 0,
        },
        brows_smile = {
            oscillateBase = 0,
            oscillateAmp = 0,
            oscillateFreq = 0,
            fadeTarget = 0,
            spikeTarget = 0,
        },
        brows_smile2 = {
            oscillateBase = 0,
            oscillateAmp = 0,
            oscillateFreq = 0,
            fadeTarget = 0,
            spikeTarget = 0,
        },
        brows_dejected = {
            oscillateBase = 0.25,
            oscillateAmp = 0.05,
            oscillateFreq = 1.5,
            fadeTarget = 0,
            spikeTarget = 0.30,
        },
        brows_dejected2 = {
            oscillateBase = 0.20,
            oscillateAmp = 0.05,
            oscillateFreq = 1.5,
            fadeTarget = 0,
            spikeTarget = 0.25,
        },
        brows_smug = {
            oscillateBase = 0,
            oscillateAmp = 0,
            oscillateFreq = 0,
            fadeTarget = 0,
            spikeTarget = 0,
        },
        brows_smug2 = {
            oscillateBase = 0,
            oscillateAmp = 0,
            oscillateFreq = 0,
            fadeTarget = 0,
            spikeTarget = 0,
        },
        brows_wink_left = {
            oscillateBase = 0,
            oscillateAmp = 0,
            oscillateFreq = 0,
            fadeTarget = 0,
            spikeTarget = 0,
        },
        brows_wink_right = {
            oscillateBase = 0,
            oscillateAmp = 0,
            oscillateFreq = 0,
            fadeTarget = 0,
            spikeTarget = 0,
        },
        brows_up = {
            oscillateBase = 0.10,
            oscillateAmp = 0.05,
            oscillateFreq = 1.5,
            fadeTarget = 0.05,
            spikeTarget = 0.05,
        },
        brows_down = {
            oscillateBase = 0.60,
            oscillateAmp = 0.10,
            oscillateFreq = 2.0,
            fadeTarget = 0.02,
            spikeTarget = 0.70,
        },

        -- ===================================
        -- 嘴部
        -- ===================================
        mouth_surprised = {
            oscillateBase = 0.12,
            oscillateAmp = 0.03,
            oscillateFreq = 2.0,
            fadeTarget = 0.08,
            spikeTarget = 0.05,
        },
        mouth_surprised2 = {
            oscillateBase = 0.10,
            oscillateAmp = 0.03,
            oscillateFreq = 2.2,
            fadeTarget = 0.06,
            spikeTarget = 0.05,
        },
        mouth_surprised3 = {
            oscillateBase = 0.08,
            oscillateAmp = 0.02,
            oscillateFreq = 2.4,
            fadeTarget = 0.05,
            spikeTarget = 0.05,
        },
        mouth_surprised4 = {
            oscillateBase = 0.06,
            oscillateAmp = 0.02,
            oscillateFreq = 2.5,
            fadeTarget = 0.04,
            spikeTarget = 0.05,
        },
        mouth_pout = {
            oscillateBase = 0.15,
            oscillateAmp = 0.05,
            oscillateFreq = 2.0,
            fadeTarget = 0,
            spikeTarget = 0.30,
        },
        mouth_pout2 = {
            oscillateBase = 0.12,
            oscillateAmp = 0.04,
            oscillateFreq = 2.2,
            fadeTarget = 0,
            spikeTarget = 0.25,
        },
        mouth_pout3 = {
            oscillateBase = 0.10,
            oscillateAmp = 0.03,
            oscillateFreq = 2.4,
            fadeTarget = 0,
            spikeTarget = 0.20,
        },
        mouth_pout4 = {
            oscillateBase = 0.08,
            oscillateAmp = 0.02,
            oscillateFreq = 2.6,
            fadeTarget = 0,
            spikeTarget = 0.15,
        },
        mouth_grin = {
            oscillateBase = 0.05,
            oscillateAmp = 0.02,
            oscillateFreq = 2.5,
            fadeTarget = 0,
            spikeTarget = 0.30,
        },
        mouth_grin2 = {
            oscillateBase = 0.04,
            oscillateAmp = 0.02,
            oscillateFreq = 2.5,
            fadeTarget = 0,
            spikeTarget = 0.25,
        },
        mouth_grin3 = {
            oscillateBase = 0.03,
            oscillateAmp = 0.01,
            oscillateFreq = 2.5,
            fadeTarget = 0,
            spikeTarget = 0.20,
        },
        mouth_smile = {
            oscillateBase = 0,
            oscillateAmp = 0,
            oscillateFreq = 0,
            fadeTarget = 0,
            spikeTarget = 0,
        },
        mouth_smile2 = {
            oscillateBase = 0,
            oscillateAmp = 0,
            oscillateFreq = 0,
            fadeTarget = 0,
            spikeTarget = 0,
        },
        mouth_smile3 = {
            oscillateBase = 0,
            oscillateAmp = 0,
            oscillateFreq = 0,
            fadeTarget = 0,
            spikeTarget = 0,
        },
        mouth_smile4 = {
            oscillateBase = 0,
            oscillateAmp = 0,
            oscillateFreq = 0,
            fadeTarget = 0,
            spikeTarget = 0,
        },
        mouth_smile5 = {
            oscillateBase = 0,
            oscillateAmp = 0,
            oscillateFreq = 0,
            fadeTarget = 0,
            spikeTarget = 0,
        },
        mouth_smile6 = {
            oscillateBase = 0,
            oscillateAmp = 0,
            oscillateFreq = 0,
            fadeTarget = 0,
            spikeTarget = 0,
        },
        mouth_happy = {
            oscillateBase = 0,
            oscillateAmp = 0,
            oscillateFreq = 0,
            fadeTarget = 0,
            spikeTarget = 0,
        },
        mouth_happy2 = {
            oscillateBase = 0,
            oscillateAmp = 0,
            oscillateFreq = 0,
            fadeTarget = 0,
            spikeTarget = 0,
        },
        mouth_happy3 = {
            oscillateBase = 0,
            oscillateAmp = 0,
            oscillateFreq = 0,
            fadeTarget = 0,
            spikeTarget = 0,
        },
        mouth_happy4 = {
            oscillateBase = 0,
            oscillateAmp = 0,
            oscillateFreq = 0,
            fadeTarget = 0,
            spikeTarget = 0,
        },
        mouth_sad = {
            oscillateBase = 0.50,
            oscillateAmp = 0.08,
            oscillateFreq = 1.8,
            fadeTarget = 0.05,
            spikeTarget = 0.60,
        },
        mouth_sad2 = {
            oscillateBase = 0.45,
            oscillateAmp = 0.08,
            oscillateFreq = 2.0,
            fadeTarget = 0.05,
            spikeTarget = 0.55,
        },
        mouth_sad3 = {
            oscillateBase = 0.40,
            oscillateAmp = 0.06,
            oscillateFreq = 2.1,
            fadeTarget = 0.03,
            spikeTarget = 0.50,
        },
        mouth_sad4 = {
            oscillateBase = 0.35,
            oscillateAmp = 0.05,
            oscillateFreq = 2.2,
            fadeTarget = 0.03,
            spikeTarget = 0.45,
        },
        mouth_sad5 = {
            oscillateBase = 0.30,
            oscillateAmp = 0.04,
            oscillateFreq = 2.3,
            fadeTarget = 0.02,
            spikeTarget = 0.40,
        },
        mouth_gape = {
            oscillateBase = 0.15,
            oscillateAmp = 0.05,
            oscillateFreq = 1.8,
            fadeTarget = 0.10,
            spikeTarget = 0.0,
        },
        mouth_gape2 = {
            oscillateBase = 0.13,
            oscillateAmp = 0.04,
            oscillateFreq = 1.9,
            fadeTarget = 0.08,
            spikeTarget = 0.0,
        },
        mouth_gape3 = {
            oscillateBase = 0.11,
            oscillateAmp = 0.03,
            oscillateFreq = 2.0,
            fadeTarget = 0.06,
            spikeTarget = 0.0,
        },
        mouth_gape4 = {
            oscillateBase = 0.09,
            oscillateAmp = 0.02,
            oscillateFreq = 2.1,
            fadeTarget = 0.05,
            spikeTarget = 0.0,
        },
        mouth_Open = {
            oscillateBase = 0.15,
            oscillateAmp = 0.05,
            oscillateFreq = 1.8,
            oscillateBeatDelta = 0.7,
            oscillateDecay = false,
            fadeTarget = 0.12,
            spikeTarget = 0.05,
        },
        mouth_Open2 = {
            oscillateBase = 0.14,
            oscillateAmp = 0.04,
            oscillateFreq = 2.0,
            oscillateDecay = false,
            fadeTarget = 0.10,
            spikeTarget = 0.05,
        },
        mouth_Open3 = {
            oscillateBase = 0.12,
            oscillateAmp = 0.03,
            oscillateFreq = 2.1,
            oscillateDecay = false,
            fadeTarget = 0.08,
            spikeTarget = 0.05,
        },
        mouth_Open4 = {
            oscillateBase = 0.10,
            oscillateAmp = 0.02,
            oscillateFreq = 2.2,
            oscillateDecay = false,
            fadeTarget = 0.06,
            spikeTarget = 0.05,
        },
        mouth_displeased = {
            oscillateBase = 0.10,
            oscillateAmp = 0.03,
            oscillateFreq = 2.0,
            fadeTarget = 0,
            spikeTarget = 0.20,
        },
        mouth_neko = {
            oscillateBase = 0,
            oscillateAmp = 0,
            oscillateFreq = 0,
            fadeTarget = 0,
            spikeTarget = 0,
        },
        mouth_chewing = {
            oscillateBase = 0,
            oscillateAmp = 0,
            oscillateFreq = 0,
            fadeTarget = 0,
            spikeTarget = 0,
        },

        -- ===================================
        -- 眼睛特殊（除 eyes_look_up/down 外均无动作）
        -- ===================================
        eyes_shrink = {
            oscillateBase = 0,
            oscillateAmp = 0,
            oscillateFreq = 0,
            fadeTarget = 0,
            spikeTarget = 0,
        },
        eyes_look_up = {
            oscillateBase = 0,
            oscillateAmp = 0,
            oscillateFreq = 0,
            fadeTarget = 0,
            spikeTarget = 0,
        },
        eyes_look_down = {
            oscillateBase = 0,
            oscillateAmp = 0,
            oscillateFreq = 0,
            fadeTarget = 0,
            spikeTarget = 0,
        },
        eyes_look_left = {
            oscillateBase = 0,
            oscillateAmp = 0,
            oscillateFreq = 0,
            fadeTarget = 0,
            spikeTarget = 0,
        },
        eyes_look_right = {
            oscillateBase = 0,
            oscillateAmp = 0,
            oscillateFreq = 0,
            fadeTarget = 0,
            spikeTarget = 0,
        },
        eyes_sqgg = {
            oscillateBase = 0,
            oscillateAmp = 0,
            oscillateFreq = 0,
            fadeTarget = 0,
            spikeTarget = 0,
        },
        eyes_X = {
            oscillateBase = 0,
            oscillateAmp = 0,
            oscillateFreq = 0,
            fadeTarget = 0,
            spikeTarget = 0,
        },
        eyes_AX = {
            oscillateBase = 0,
            oscillateAmp = 0,
            oscillateFreq = 0,
            fadeTarget = 0,
            spikeTarget = 0,
        },
        eyes_BQ1 = {
            oscillateBase = 0,
            oscillateAmp = 0,
            oscillateFreq = 0,
            fadeTarget = 0,
            spikeTarget = 0,
        },
        eyes_BQ2 = {
            oscillateBase = 0,
            oscillateAmp = 0,
            oscillateFreq = 0,
            fadeTarget = 0,
            spikeTarget = 0,
        },
        eyes_BQ3 = {
            oscillateBase = 0,
            oscillateAmp = 0,
            oscillateFreq = 0,
            fadeTarget = 0,
            spikeTarget = 0,
        },

        -- ===================================
        -- 面部特效 / 其他
        -- ===================================
        face_HY1 = {
            oscillateBase = 0,
            oscillateAmp = 0,
            oscillateFreq = 0,
            fadeTarget = 0,
            spikeTarget = 0,
        },
        face_HY2 = {
            oscillateBase = 0,
            oscillateAmp = 0,
            oscillateFreq = 0,
            fadeTarget = 0,
            spikeTarget = 0,
        },
        face_HY3 = {
            oscillateBase = 0,
            oscillateAmp = 0,
            oscillateFreq = 0,
            fadeTarget = 0,
            spikeTarget = 0,
        },
        face_Tears = {
            oscillateBase = 0.45,
            oscillateAmp = 0.15,
            oscillateFreq = 1.0,
            fadeTarget = 0,
            spikeTarget = 0,
        },
        face_Teeth = {
            oscillateBase = 0.05,
            oscillateAmp = 0.02,
            oscillateFreq = 1.5,
            fadeTarget = 0,
            spikeTarget = 0.40,
        },
        face_tongue = {
            oscillateBase = 0,
            oscillateAmp = 0,
            oscillateFreq = 0,
            fadeTarget = 0,
            spikeTarget = 0,
        },
        face_tongue_forward = {
            oscillateBase = 0,
            oscillateAmp = 0,
            oscillateFreq = 0,
            fadeTarget = 0,
            spikeTarget = 0,
        },
        face_tongue_bone = {
            oscillateBase = 0,
            oscillateAmp = 0,
            oscillateFreq = 0,
            fadeTarget = 0,
            spikeTarget = 0,
        },
    },

    -- ============================================================================
    -- 眼球运动配置
    -- 濒死期不振荡，强直期上翻 0.45，死后回正
    -- ============================================================================
    eyeControl = "flexeye",
    eyeControlConfig = {
        upL   = "eyes_look_up",
        downL = "eyes_look_down",
        upR   = "eyes_look_up",
        downR = "eyes_look_down",
    },
    eyeConfigTemplate = {
        horiz = {
            oscillateBase = 0,
            oscillateAmp  = 0,
            oscillateFreq = 0,
            fadeTarget    = 0,
            spikeTarget   = 0,
        },
        vert = {
            oscillateBase = 0,
            oscillateAmp  = 0,
            oscillateFreq = 0,
            fadeTarget    = 0,
            spikeTarget   = 0.45,
        },
    },
}
